config/routes.rb
Rails.application.routes.draw do
  get 'interventions/new'
  get 'interventions/update_buildings', as: 'update_buildings'
  get 'interventions/update_batteries', as: 'update_batteries'
  get 'interventions/update_columns', as: 'update_columns'
  get 'interventions/update_elevators', as: 'update_elevators'
  get 'interventions/update_element_path', as: 'update_element_path'  
  #post 'interventions/create', as: 'create_path'
  
  get 'interventions/new', as: 'new_path'

  #get '/INTERVENTION_FORM', as: 'new_path'



  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  resources :interventions do
    collection do
      get 'get_buildings', to: "interventions#get_buildings"
    end 
  end

  resources :addresses, only: %i[index]

  resources :leads
  resources :employees

  resources :customers
  resources :buildings

  resources :quotes, only: %i[user_quotes new create]

  root to: 'static_pages#index'
  get 'static_pages/residential'
  get 'static_pages/corporate'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations', sessions: 'users/sessions'
             },
             path_names: {
               sign_in: 'sign_in',
               sign_out: 'sign_out',
               password: 's',
               confirmation: 'v'
             }

  get 'my_quotes' => 'quotes#user_quotes', as: :my_quotes
  get 'my_leads' => 'leads#user_leads', as: :my_leads 

  resource :messages do
    collection { post 'reply' }
  end
end

app/views/partials/_alerts.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
       	 toastr['<%= type %>']('<%= f[1] %>');
       <% end %>
  </script>
<% end %>

app/views/partials/_footer.html.erb
<!-- FOOTER -->
<footer id="footer">
  <div class="container mb-10 pt-30">
    <div class="row">
      <!-- col #1 -->
      <div class="col-md-7">
        <h3 class="letter-spacing-1 mb-25">WHY US?</h3>
        <!-- Small Description -->
        <p class="mb-20">
          Our mission is to make you go up. We are number one in the domain, and we supply everyone with the best elevators there are, from your Grandparents to Google. We take good care of all of your requests and we are conscientious to achieve your goals.
        </p>
        <h2 class="mb-0">(581) 701-0303</h2>
      </div>
      <!-- /col #1 -->
      <!-- col #2 -->
      <div class="col-md-5">
        <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>
        <!-- Newsletter Form -->
        <p>Subscribe to Our Newsletter to get Important News & Offers</p>
        <form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
            <input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
            <span class="input-group-btn">
              <button class="btn btn-red btn-red-click" type="submit">Subscribe</button>
            </span>
          </div>
        </form>
        <!-- /Newsletter Form -->
      </div>
      <!-- /col #2 -->
    </div>
  </div>
  <div class="copyright p-10">
    <div class="container">
      <ul class="float-right m-0 list-inline mobile-block">
        <li><a href="#">Terms &amp; Conditions</a></li>
        <li>&bull;</li>
        <li><a href="#">Privacy</a></li>
      </ul>
      &copy; All Rights Reserved, RocketElevator LTD
    </div>
  </div>
</footer>
<!-- /FOOTER -->

app/views/partials/_header.html.erb
<div id="header" class="navbar-toggleable-md sticky header-md clearfix">
  <!-- TOP NAV -->
  <header id="topNav">
    <div class="container" id="top">
      <!-- Mobile Menu Button -->
      <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <!-- Logo -->
      <%= link_to image_tag('logo/R2.png'), root_path, class: "logo float-left scrollTo", 'data-turbolinks': false %>
      <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
        <nav class="nav-main">
          <ul id="topMain" class="nav nav-pills nav-main nav-hover nav-onepage">
            <li class="active"><!-- HOME -->
              <%= link_to 'HOME', root_path, 'data-turbolinks': false %>
            </li>
            <li class="dropdown nav-animate-fadeIn resp-active"><!-- SERVICES -->
              <%= link_to 'SERVICES', root_path(anchor: "services"), 'data-turbolinks': false %>
              <ul class="dropdown-menu">
                <li class="dropdown">
                  <a href="/static_pages/residential">RESIDENTIAL SERVICES</a>
                </li>
                <li class="dropdown">
                  <a href="/static_pages/corporate">CORPORATE SERVICES</a>
                </li>
                <li class="dropdown">
                  <%= link_to 'GET A QUOTE', new_quote_path %>
                </li>
              </ul>
            </li>
            <li><!-- PORTFOLIO -->
              <%= link_to 'PORTFOLIO', root_path(anchor: "portfolio"), 'data-turbolinks': false %>
            </li>
            <li><!-- NEWS -->
              <%= link_to 'NEWS', root_path(anchor: "news"), 'data-turbolinks': false %>
            </li>
            <li><!-- CLIENTS -->
              <%= link_to 'CLIENTS', root_path(anchor: "clients"), 'data-turbolinks': false %>
            </li>
            <li><!-- CONTACT -->
              <%= link_to 'CONTACT', root_path(anchor: "contact"), 'data-turbolinks': false %>
            </li>
            <% if user_signed_in? %>
              <li><!-- Interventions Form -->
                <%= link_to 'Interventions', "/interventions/new" %>
              </li>
            <% end %>
            <% if can? :read, Quote %>
              <li><!-- BACKOFFICE -->
                <%= link_to 'BACKOFFICE', rails_admin_path %>
              </li>
            <% end %>
            <% if user_signed_in? %>
              <!-- ACCOUNT DROPDOWN -->
              <li class="dropdown nav-animate-fadeIn resp-active">
                <%= link_to 'MY ACCOUNT', edit_user_registration_path %>
                <ul class="dropdown-menu">
                  <li class="dropdown">
                    <%= link_to 'MY ACCOUNT', edit_user_registration_path %>
                  </li>
                  <li class="dropdown">
                    <%= link_to 'MY QUOTES', my_quotes_path %>
                  </li>
                  <li class="dropdown">
                    <%= link_to 'MY LEADS', my_leads_path %>
                  </li>
                  <li class="dropdown">
                    <%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %>
                  </li>
                </li>
              <% else %>
                <li><!-- REGISTER -->
                  <%= link_to 'REGISTER', new_user_registration_path %>
                </li>
                <li><!-- SIGN IN -->
                  <%= link_to 'SIGN IN', new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>
</div>
<!-- /Top Nav -->