config/routes.rb
Rails.application.routes.draw do
  get 'interventions/new'
  get 'interventions/update_buildings', as: 'update_buildings'
  get 'interventions/update_batteries', as: 'update_batteries'
  get 'interventions/update_columns', as: 'update_columns'
  get 'interventions/update_elevators', as: 'update_elevators'
  get 'interventions/update_element_path', as: 'update_element_path'  
  #post 'interventions/create', as: 'create_path'
  
  get 'interventions/new', as: 'new_path'

  #get '/INTERVENTION_FORM', as: 'new_path'



  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  resources :interventions do
    collection do
      get 'get_buildings', to: "interventions#get_buildings"
    end 
  end

  resources :addresses, only: %i[index]

  resources :leads
  resources :employees

  resources :customers
  resources :buildings

  resources :quotes, only: %i[user_quotes new create]

  root to: 'static_pages#index'
  get 'static_pages/residential'
  get 'static_pages/corporate'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations', sessions: 'users/sessions'
             },
             path_names: {
               sign_in: 'sign_in',
               sign_out: 'sign_out',
               password: 's',
               confirmation: 'v'
             }

  get 'my_quotes' => 'quotes#user_quotes', as: :my_quotes
  get 'my_leads' => 'leads#user_leads', as: :my_leads 

  resource :messages do
    collection { post 'reply' }
  end
end

app/models/intervention.rb
class Intervention < ApplicationRecord    
    belongs_to :customer
    belongs_to :employee
    belongs_to :battery
    belongs_to :column
    belongs_to :elevator
    belongs_to :building    
    #validates :battery_id, :column_id, :elevator_id, :employee_id, allow_blank: true

    after_initialize :set_defaults

  def set_defaults
    self.result ||= "Incomplete"
    self.status ||= "Pending"
  end
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController 
  require 'zendesk_api'

  def new
    @employees = Employee.all
    @customers = Customer.all 
    @buildings = Building.all     
    @batteries  = Battery.all
    @columns   = Column.all
    @elevators = Elevator.all   

  end

  def show   
  end

  def create
    @employee = Employee.new
    @customer = Customer.new 
    @building = Building.new    
    @battery  = Battery.new
    @column   = Column.new
    @elevator = Elevator.new     
    
    @intervention = Intervention.new(intervention_params) 
    @employee = Employee.new(employee_params)    
    @customer = Customer.new(customer_params)
    @building = Building.new(building_params)     
    @battery  = Battery.new(battery_params)
    @column   = Column.new(column_params)
    @elevator = Elevator.new(elevator_params)    

    @intervention.employee_id = @employee.id
    @intervention.customer_id = @customer.id
    @intervention.building_id = @building.id 
    @intervention.battery_id = @battery.id
    @intervention.column_id = @column.id
    @intervention.elevator_id = @elevator.id    

      respond_to do |format|
        if @intervention.save
          #create_ticket_zendesk  
          format.html do
            redirect_to new_path_url, notice: 'Quote created successfully!'
          end
          format.json { render json: @intervention.to_json }
        else
          format.html { render 'new'} ## Specify the format in which you are rendering "new" page
          format.json { render json: @intervention.errors } ## You might want to specify a json format as well
        end
      end

    # @intervention.save
    # create_ticket_zendesk  
    
    # respond_to do |format|
    #   if @intervention.save
    #     format.html do
    #       redirect_to new_path_url, notice: 'Quote created successfully!'
    #     end              
    #   end
    # end
  end

  def update_buildings
    @customer = Customer.find(params[:customer_id])    
    @buildings = @customer.buildings
    respond_to do |format|
      format.json {render :json => {building: @buildings}}
    end
  end

  def update_batteries
    @buildings = Building.find(params[:building_id])    
    @batteries =  @buildings.batteries
    respond_to do |format|
      format.json {render :json => {battery: @batteries}}
    end
  end

  def update_columns
    @batteries = Battery.find(params[:battery_id])    
    @columns = @batteries.columns
    respond_to do |format|
      format.json {render :json => {column: @columns}}
    end
  end

  def update_elevators
    @columns = Column.find(params[:column_id])    
    @elevators = @columns.elevators
    respond_to do |format|
      format.json {render :json => {elevator: @elevators}}
    end
  end  
end

# def create_ticket_zendesk
#   client = ZendeskAPI::Client.new do |config|
#     config.url = ENV["ZENDESK_URL"]
#     config.username = ENV["ZENDESK_USERNAME"]
#     config.token = ENV["ZENDESK_TOKEN"]
#   end  
#   ZendeskAPI::Ticket.create!(client, :subject => "New intervention request", :comment => @intervention.to_json, :submitter_id => @intervention.customer_id, :type => "problem")
# end


# def create_ticket_zendesk
#   client = ZendeskAPI::Client.new do |config|
#     # Mandatory:
  
#     config.url = "https://samcoutinho.zendesk.com" # e.g. https://mydesk.zendesk.com/api/v2
  
#     # Basic / Token Authentication
#     config.username = "samcoutinho@yahoo.com.br"
  
#     # Choose one of the following depending on your authentication choice
#     config.token = "XkgTD1t6XzkPvoJqWWVaYf9THLAn4pcBKs5fjNcZ"
#     #config.password = ""
#   end
  
#   ZendeskAPI::Ticket.create!(client, :subject => @intervention, :comment => { :value => "This is a test" }, :submitter_id => @intervention.customer_id, :priority => "urgent")

# end

private 
  def intervention_params
    params.permit(
      :customer_id,
      :employee_id,
      :battery_id,
      :column_id,
      :elevator_id,
      :building_id,
      :author,
      :start_date_and_time,
      :end_date_and_time,
      :result,
      :report,
      :status
    )
  end

  def employee_params
    params.require(:employee).permit(
      :id,
      :first_name,
      :last_name,
      :function,
      :phone,
      :email,
      :user_id    
    )
  end

  def customer_params
    params.require(:customer).permit(
      :id,
      :user_id,
      :company_name,
      :company_contact_full_name,
      :company_contact_phone,
      :company_contact_email,
      :company_description,    
      :technical_authority_full_name,
      :technical_authority_phone_number,
      :technical_manager_email_service,
      :address_id    
    )
  end

  def building_params
    params.require(:building).permit(
      :id,
      :customer_id,
      :admin_contact_id,
      :technical_contact_id,
      :administrator_full_name,
      :administrator_email,
      :administrator_phone_number,    
      :technical_contact_full_name,
      :technical_contact_email,
      :technical_contact_phone,
      :building_detail_id,
      :address_id  
    )
  end

  def battery_params
    params.require(:battery).permit(
      :id,
      :building_id,
      :employee_id,
      :battery_type,
      :battery_status,
      :date_of_commissioning,
      :date_of_last_inspection,    
      :certificate_of_operations,
      :information,
      :notes    
    )
  end

  def column_params
    params.require(:column).permit(
      :id,
      :battery_id,
      :column_type,
      :column_status,
      :number_of_floors_served,
      :information,
      :notes     
    )
  end

  def elevator_params
    params.require(:elevator).permit(
      :id,
      :column_id,
      :serial_number,
      :elevator_model,
      :elevator_type,
      :elevator_status,
      :date_of_commissioning,     
      :date_of_last_inspection,
      :certificate_of_inspection,
      :information,
      :notes
    )
  end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/get_buildings.js.erb
<%# $(document).ready ->
  $(".customer_selection").on "change", ->
    $.ajax
      url: "/interventions/get_buildings"
      type: "GET"
      dataType: "script"
      data:
        customer_id: $('.customer_selection option:selected').val()
    $('.building_selection').empty();
    $('.building_selection').append( $('<option>Select the Contact</option>'));
    <% @buildings.each do |building| %>
    

app/views/interventions/new.html.erb
<p id="notice"><%= notice %></p>
<head>
  
</head>


<div class="container p-3 my-3 border" style="background-color: lightsteelblue; vertical-align: top;">

    <div class="card-block" style="background-color: lightsteelblue; vertical-align: top;">
        <div class="row">
            
            <div class="col-sm-6">	
                <h1>Interventions Form</h1>
                <%= simple_form_for :search, url: {action: "create"} do |f| %>
            
                    <%= label_tag(:id, "Select a Employee:") %>
                    <%= collection_select(:employee, :id, Employee.all, :user_id, :first_name, prompt: "None", include_blank: true) %>                                          
                                        
                    <%= label_tag(:id, "Select a Customer:") %>
                    <%= collection_select(:customer, :id, Customer.all, :user_id, :company_name, include_blank: true,) %>
                    
                    <%= label_tag(:id, "Select a Building:") %>
                    <%= collection_select(:building, :id, @buildings, :id, :id, include_blank: true) %>

                    <%= label_tag(:id, "Select a Battery:") %>
                    <%= collection_select(:battery, :id, @batteries, :id, :id, include_blank: true) %>                                
           
                    <%= label_tag(:id, "Select a Column:") %>
                    <%= collection_select(:column, :id, @columns, :id, :id, prompt: "None", include_blank: true) %>
                                
                    <%= label_tag(:id, "Select a Elevator:") %>
                    <%= collection_select(:elevator, :id, @elevators, :id, :id, prompt: "None", include_blank: true) %> 

                    <%= label_tag(:description, "Description:") %>
                    <%= text_area_tag(:report) %>

                    <%= submit_tag "Create"%>
                <% end %>         

            </div>
                  
        </div>		
    </div>				
</div>
<script>
        $(document).ready(function() {                    
                $('#customer_id').change(function() {
                    console.log("customer_selection----------------")
                    $.ajax({
                        url: "<%= update_buildings_path %>",
                    data: {
                        customer_id: $('#customer_id').val()
                    },
                    dataType: "json",
                    success: function (response)
                        {
                            console.log(response);
                            var building = response["building"];
                            $("#building_id").empty(); // Empty the chosen dropdown
                            $("#building_id").append('<option>Select a building</option>');
                            for(var i = 0; i < building.length; i++){
                                $("#building_id").append('<option value="' + building[i]["id"] + '"> building id: ' +building[i]["id"] + '</option>');
                            }
                        }
                });
            });
        });

        $(document).ready(function() {                    
                $('#building_id').change(function() {
                    console.log("battery_selection----------------")
                    $.ajax({
                        url: "<%= update_batteries_path %>",
                    data: {
                        building_id: $('#building_id').val()
                    },
                    dataType: "json",
                    success: function (response)
                        {
                            console.log(response);
                            var battery = response["battery"];
                            $("#battery_id").empty(); // Empty the chosen dropdown
                            $("#battery_id").append('<option>Select a battery</option>');
                            for(var i = 0; i < battery.length; i++){
                                $("#battery_id").append('<option value="' + battery[i]["id"] + '"> battery id: ' +battery[i]["id"] + '</option>');
                            }
                        }
                });
            });
        });

        $(document).ready(function() {                    
                $('#battery_id').change(function() {
                    console.log("column_selection----------------")
                    $.ajax({
                        url: "<%= update_columns_path %>",
                    data: {
                        battery_id: $('#battery_id').val()
                    },
                    dataType: "json",
                    success: function (response)
                        {
                            console.log(response);
                            var column = response["column"];
                            $("#column_id").empty(); // Empty the chosen dropdown
                            $("#column_id").append('<option>None</option>');
                            for(var i = 0; i < column.length; i++){
                                $("#column_id").append('<option value="' + column[i]["id"] + '"> column id: ' +column[i]["id"] + '</option>');
                            }
                        }
                });
            });
        });
        
        $(document).ready(function() {                    
                $('#column_id').change(function() {
                    console.log("column_selection----------------")
                    $.ajax({
                        url: "<%= update_elevators_path %>",
                    data: {
                        column_id: $('#column_id').val()
                    },
                    dataType: "json",
                    success: function (response)
                        {
                            console.log(response);
                            var elevator = response["elevator"];
                            $("#elevator_id").empty(); // Empty the chosen dropdown
                            $("#elevator_id").append('<option>None</option>');
                            for(var i = 0; i < elevator.length; i++){
                                $("#elevator_id").append('<option value="' + elevator[i]["id"] + '"> elevator id: ' +elevator[i]["id"] + '</option>');
                            }
                        }
                });
            });
        });         
    </script>
            
            

      